## Linear Algebra

In [1]:
import math
import random
import numpy as np
import scipy
import sympy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# vectors
v = [3, 2]
print(v) # as a list
v = np.array([3, 2])
print(v) # as an array

[3, 2]
[3 2]


In [3]:
# multidimensional vectors
v = np.array([4, 1, 2])
print(v)
v = np.array([6,1,5,8,3])
print(v)

[4 1 2]
[6 1 5 8 3]


In [4]:
# adding vectors
v = np.array([3, 2])
w = np.array([2, -1])
v_plus_w = v + w
print(v_plus_w)

[5 1]


In [5]:
# adding vectors is commutative (v+w == w+v)
w_plus_v = w + v
print(w_plus_v)

[5 1]


In [6]:
# scalars
v = np.array([3, 1])
scaled_v = 2.0 * v
print(scaled_v)

[6. 2.]


In [7]:
# basis vectors
i_hat = np.array([1, 0])
j_hat = np.array([0, 1])
basis = np.array(
    [[1, 0],
     [0, 1]]
)
print(i_hat)
print(j_hat)
print(basis)

[1 0]
[0 1]
[[1 0]
 [0 1]]


In [8]:
# scaled basis
i_scaled = 3.0 * i_hat
j_scaled = 2.0 * j_hat
print(i_scaled)
print(j_scaled)

[3. 0.]
[0. 2.]


In [9]:
# matrix multiplication
basis = np.array(
    [[3, 0],
     [0, 2]]
)
v = np.array([1, 1])
new_v = basis.dot(v)
print(new_v)

[3 2]


In [10]:
# transpose (rows to columns)
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([1, 1])
new_v = basis.dot(v)
print(new_v)

[2 3]


In [11]:
# rows vs columns matters in matrix multiplication!
i_hat = np.array([2, 1])
j_hat = np.array([-3, 3])
incorrect = np.array([i_hat, j_hat])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([1, 1])
new_v = basis.dot(v)
incorrect_v = incorrect.dot(v)
print('Without transposition:', incorrect_v)
print('With transposition:', new_v)

Without transposition: [3 0]
With transposition: [-1  4]


In [12]:
# transform vector
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([2, 1])
new_v = basis.dot(v)
print(new_v)

[4 3]


In [13]:
# linear transformation with rotate, shear, and flip
i_hat = np.array([2, 3])
j_hat = np.array([2, -1])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([2, 1])
new_v = basis.dot(v)
print(new_v)

[6 5]


In [14]:
# combining transformations
i_hat1 = np.array([0, 1])
j_hat1 = np.array([-1, 0])
transform1 = np.array([i_hat1, j_hat1]).transpose()

i_hat2 = np.array([1, 0])
j_hat2 = np.array([1, 1])
transform2 = np.array([i_hat2, j_hat2]).transpose()

combined = transform2 @ transform1

print('Combined matrix:\n', combined)
v = np.array([1, 2])
print(combined.dot(v))

Combined matrix:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


In [15]:
# can also apply in order
rotated = transform1.dot(v)
sheared = transform2.dot(rotated)
print(sheared)

[-1  1]


In [16]:
# transformation order matters!
combined = transform1 @ transform2
print('Combined matrix:\n', combined)
v = np.array([1, 2])
print(combined.dot(v))

Combined matrix:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


In [17]:
# determinants (vector areas)
i_hat = np.array([3, 0])
j_hat = np.array([0, 2])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

6.0


In [18]:
# shear determinant (diagonal)
i_hat = np.array([1, 0])
j_hat = np.array([1, 1])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

1.0


In [19]:
# determinant negative (orientation flipped)
i_hat = np.array([-2, 1])
j_hat = np.array([1, 2])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

-5.000000000000001


In [20]:
# determinant for showing linear dependence
i_hat = np.array([-2, 1])
j_hat = np.array([3, -1.5])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

0.0


In [21]:
# solving system of equations using linear algebra
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = sympy.Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])
inverse = A.inv()
identity = inverse * A
print('INVERSE:', inverse)
print('IDENTITY:', identity)
B = sympy.Matrix([
    44,
    56,
    72
])
# AX = B
# X = A.inv * B
X = A.inv() * B
print('Solution:', X)

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
Solution: Matrix([[2], [34], [-8]])


In [22]:
# eigendecomposition
A = np.array([
    [1, 2],
    [4, 5]
])
eigenvals, eigenvecs = np.linalg.eig(A)
print('EIGENVALUES:', eigenvals)
print('EIGENVECTORS:', eigenvecs)
# A = Q^Q.inv, where ^ is the diagonal form of eigenvalues
Q = eigenvecs
R = np.linalg.inv(Q)
L = np.diag(eigenvals)
B = Q @ L @ R
print('MATRIX REBUILT:', B)

EIGENVALUES: [-0.46410162  6.46410162]
EIGENVECTORS: [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]
MATRIX REBUILT: [[1. 2.]
 [4. 5.]]


In [23]:
# exercise 1
i_hat = np.array([2, 0])
j_hat = np.array([0, 1.5])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([1, 2])
new_v = basis.dot(v)
print(new_v)

[2. 3.]


In [24]:
# exercise 2
i_hat = np.array([-2, 1])
j_hat = np.array([1, -2])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([1, 2])
new_v = basis.dot(v)
print(new_v)

[ 0 -3]


In [25]:
# exercise 3
i_hat = np.array([1, 0])
j_hat = np.array([2, 2])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

2.0


In [26]:
# exercise 4

# 2+ linear transformations can be done in a single linear transformation,
# so long as the underlying linear transformations are applied
# in the correct order. For example:
basis1 = np.array([
    [1, 1],
    [0, 1]
])
basis2 = np.array([
    [0, -1],
    [-1, 0]
])
single = basis2 @ basis1
print(single)
v = np.array([2, 1])
new_v = single.dot(v)
print(new_v)

[[ 0 -1]
 [-1 -1]]
[-1 -3]


In [27]:
# exercise 5
A = sympy.Matrix([
    [3, 1, 0],
    [2, 4, 1],
    [3, 1, 8]
])
B = sympy.Matrix([
    54,
    12,
    6
])
X = A.inv() * B
print(X)

Matrix([[99/5], [-27/5], [-6]])


In [28]:
# exercise 6
basis = np.array([
    [2, 1],
    [6, 3]
])
determinant = np.linalg.det(basis)
print(determinant)
print('Linearly independent? -->', determinant != 0.0)

0.0
Linearly independent? --> False
