## Linear Algebra

In [1]:
import math
import random
import numpy as np
import sympy
import matplotlib.pyplot as plt
import seaborn as sns

Linear algebra: study and manipulation of linear systems

linear algebra is often more complex than regular algebra <br>
linear algebra *should* have been called "vector algebra" or "matrix algebra"

vector: arrow in space with direction & length <br>
a vector often represents a piece of data (a single vector would be a single observation), where each variable is a component of the vector

$\vec{v} = \begin{bmatrix} x \\ y \end{bmatrix}$

In [2]:
# vectors
v = [3, 2]
print(v) # as a list
v = np.array([3, 2])
print(v) # as an array

[3, 2]
[3 2]


$\vec{v} = \begin{bmatrix} 4\\1\\2 \end{bmatrix}$

$\vec{v} = \begin{bmatrix} 6\\1\\5\\8\\3 \end{bmatrix}$

In [3]:
# multidimensional vectors
v = np.array([4, 1, 2])
print(v)
v = np.array([6,1,5,8,3])
print(v)

[4 1 2]
[6 1 5 8 3]


physics vector: a direction and magnitude <br>
math vector: a direction and scale on an XY plane <br>
computer science vector: an array of numbers storing data

In [4]:
# adding vectors
v = np.array([3, 2])
w = np.array([2, -1])
v_plus_w = v + w
print(v_plus_w)

[5 1]


Vector addition: combine movements of two vectors into a single vector

$\vec{v} = \begin{bmatrix} 3\\2 \end{bmatrix}$

$\vec{w} = \begin{bmatrix} 2\\-1 \end{bmatrix}$

$\vec{v} + \vec{w} = \begin{bmatrix} 3+2\\2+(-1) \end{bmatrix} = \begin{bmatrix} 5\\1 \end{bmatrix}$

In [5]:
# adding vectors is commutative (v+w == w+v)
w_plus_v = w + v
print(w_plus_v)

[5 1]


Vector scaling: multiplying a vector by a constant

$2\vec{v} = 2\begin{bmatrix} 3\\1 \end{bmatrix} = \begin{bmatrix} 3*2\\1*2 \end{bmatrix} = \begin{bmatrix} 6\\2 \end{bmatrix}$

scaling only changes magnitude <br>
the only exception is that scaling flips direction if scalar is negative

In [6]:
# scalars
v = np.array([3, 1])
scaled_v = 2.0 * v
print(scaled_v)

[6. 2.]


span: whole space of possible vectors (within the $n$-dimensional space where $n$ is the number of dimensions in the vectors)

**ANY NEW VECTOR CAN BE CREATED BY SCALING AND ADDING TWO VECTORS**

linear independence: when two vectors have different directions

vectors with the same direction (or can be scaled to be parallel) are *linearly dependent*.

linearly dependent vectors cannot create any new vectors alone. Linearly dependent vectors reduce the total number of dimensions in the span (linearly dependent vectors in a 3D space only exist on a 2D (or even 1D!) plane)

sometimes vectors are used to solve systems of equations, and when vectors have linear dependence, these equations can be extremely difficult or even impossible to solve.

Basis vectors: describe transformations on other vectors

$ \hat{i} = \begin{bmatrix} 1\\0 \end{bmatrix} $

$ \hat{j} = \begin{bmatrix} 0\\1 \end{bmatrix} $

$ \mathrm{basis} = \hat{i}\hat{j} = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $

In [7]:
# basis vectors
i_hat = np.array([1, 0])
j_hat = np.array([0, 1])
basis = np.array(
    [[1, 0],
     [0, 1]]
)
print(i_hat)
print(j_hat)
print(basis)

[1 0]
[0 1]
[[1 0]
 [0 1]]


matrix: collection of vectors that can have multiple rows or columns

four main transformations are scale, rotate, shear, and inversion

In [8]:
# scaled basis
i_scaled = 3.0 * i_hat
j_scaled = 2.0 * j_hat
print(i_scaled)
print(j_scaled)

[3. 0.]
[0. 2.]


Matrix vector multiplication: tracking where basis vectors land after a transformation

To transform a vector $\vec{v}$ given basis vectors $\hat{i}$ and $\hat{j}$ packaged as a matrix, use a dot product:

$ \hat{i}\hat{j}*\vec{v} =  \begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix} = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} ax + by \\ cx + dy \end{bmatrix}$

In [9]:
# matrix multiplication
basis = np.array(
    [[3, 0],
     [0, 2]]
)
v = np.array([1, 1])
new_v = basis.dot(v)
print(new_v)

[3 2]


Matrix transposition: swap rows & columns

A transposition of matrix $A$ is represented as $A^{-1}$

In [10]:
# transpose (rows to columns)
i_hat = np.array([2, 4])
j_hat = np.array([1, 3])
A = np.array([i_hat, j_hat])
print(A)
A_t = A.transpose()
print(A_t)

[[2 4]
 [1 3]]
[[2 1]
 [4 3]]


In [11]:
# translation of a vector
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([1, 1])
new_v = basis.dot(v)
print(new_v)

[2 3]


In [12]:
# rows vs columns matters in matrix multiplication!
i_hat = np.array([2, 1])
j_hat = np.array([-3, 3])
incorrect = np.array([i_hat, j_hat])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([1, 1])
new_v = basis.dot(v)
incorrect_v = incorrect.dot(v)
print('Without transposition:', incorrect_v)
print('With transposition:', new_v)

Without transposition: [3 0]
With transposition: [-1  4]


In [13]:
# transform vector
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([2, 1])
new_v = basis.dot(v)
print(new_v)

[4 3]


In [14]:
# linear transformation with rotate, shear, and flip
i_hat = np.array([2, 3])
j_hat = np.array([2, -1])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([2, 1])
new_v = basis.dot(v)
print(new_v)

[6 5]


Matrix multiplication can also be thought of as applying multiple transformations to a vector space.

matrix multiplication is not commutative! Order matters!

$ \begin{bmatrix} a & b \\ c & d \end{bmatrix}\begin{bmatrix} e & f \\ g & h \end{bmatrix} = \begin{bmatrix} ae+bg & af+bh \\ ce+dg & cf + dh \end{bmatrix}$

In [15]:
# combining transformations
i_hat1 = np.array([0, 1])
j_hat1 = np.array([-1, 0])
transform1 = np.array([i_hat1, j_hat1]).transpose()

i_hat2 = np.array([1, 0])
j_hat2 = np.array([1, 1])
transform2 = np.array([i_hat2, j_hat2]).transpose()

combined = transform2 @ transform1

print('Combined matrix:\n', combined)
v = np.array([1, 2])
print(combined.dot(v))

Combined matrix:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


In [16]:
# can also apply in order
rotated = transform1.dot(v)
sheared = transform2.dot(rotated)
print(sheared)

[-1  1]


In [17]:
# transformation order matters!
combined = transform1 @ transform2
print('Combined matrix:\n', combined)
v = np.array([1, 2])
print(combined.dot(v))

Combined matrix:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


Determinant: describes how much a sampled area in a vector space changes in scale with linear transformations
1. shears and rotations do not affect the determinant
2. increasing or decreasing scaling, increases or decreases the determinant
3. a negative determinant means orientation has flipped
4. linearly dependent transformations have a determinant of zero (space has been squashed into a lower dimension)

In [18]:
# determinants (vector areas)
i_hat = np.array([3, 0])
j_hat = np.array([0, 2])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

6.0


In [19]:
# shear determinant (diagonal)
i_hat = np.array([1, 0])
j_hat = np.array([1, 1])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

1.0


In [20]:
# determinant negative (orientation flipped)
i_hat = np.array([-2, 1])
j_hat = np.array([1, 2])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

-5.000000000000001


In [21]:
# determinant for showing linear dependence
i_hat = np.array([-2, 1])
j_hat = np.array([3, -1.5])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

0.0


Types of matrices:

Square matrix: has the same number of rows and columns <br>
primarily used to represent linear transformations and are used in many operations like decomposition.

$\begin{bmatrix} 4 & 2 & 7 \\ 5 & 1 & 9 \\ 4 & 0 & 1\end{bmatrix}$

Identity matrix: square matrix of diagonal 1's with all other values zero
important for identifying when a transformation has been undone

$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

Inverse matrix: The matrix that, when applied to its non-inverse, yields an identity matrix <br>
useful in many operations, including to solve systems of equations

$A * A^{-1} = I $

Diagonal matrix: square matrix of diagonal non-zero values, with all other values zero <br>
applied in some operations, like simple scalars applied to a vector space

$\begin{bmatrix} 2 & 0 & 0 \\ 0 & 8 & 0 \\ 0 & 0 & 3 \end{bmatrix}$

Triangular matrix: upper right triangle of values, lower left triangle of zeros <br>
useful in many operations, especially decomposition

$\begin{bmatrix} 2 & 8 & 3 \\ 0 & 6 & 5 \\ 0 & 0 & 1 \end{bmatrix}$

Sparse matrix: matrix with few non-zero elements <br>
not very useful in math, but can provide efficiencies from a computing standpoint

$\begin{bmatrix} 0 & 0 & 0 \\ 0 & 4& 0 \\ 0 & 0 & 3 \\ 0 & 0 & 0 \end{bmatrix}$

Solving systems of equations such that

$AX = B$, where

$A$ is the matrix of coefficients,
$X$ is the vector of variables, and
$B$ is the vector of solutions.

To solve,

$AX = B$

$A^{-1}AX = A^{-1}B$

$X = A^{-1}B$

In [22]:
# solving system of equations using linear algebra
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = sympy.Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])
inverse = A.inv()
identity = inverse * A
print('INVERSE:', inverse)
print('IDENTITY:', identity)
B = sympy.Matrix([
    44,
    56,
    72
])
# AX = B
# X = A.inv * B
X = A.inv() * B
print('Solution:', X)

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
Solution: Matrix([[2], [34], [-8]])


Matrix decomposition: breaking up a matrix into its basic components

Eigendecomposition breaks up a matrix into two components, eigenvalues $\lambda$ and eigenvector $v$

Eigendecomposition only works on square matrices

$ Av = \lambda v$, where 
$A$ is the parent matrix, <br>
$v$ is the eigenvalues, and <br>
$\lambda$ is the eigenvectors

to reconstruct the matrix from $\lambda$ and $v$,

$A = \lambda \Lambda \lambda^{-1} $ where <br>
$\lambda$ is the eigenvectors matrix, and <br>
$\Lambda$ is the eigenvalues in diagonal matrix form.

In [23]:
# eigendecomposition
A = np.array([
    [1, 2],
    [4, 5]
])
eigenvals, eigenvecs = np.linalg.eig(A)
print('EIGENVALUES:', eigenvals)
print('EIGENVECTORS:', eigenvecs)
# A = Q^Q.inv, where ^ is the diagonal form of eigenvalues
Q = eigenvecs
R = np.linalg.inv(Q)
L = np.diag(eigenvals)
B = Q @ L @ R
print('MATRIX REBUILT:', B)

EIGENVALUES: [-0.46410162  6.46410162]
EIGENVECTORS: [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]
MATRIX REBUILT: [[1. 2.]
 [4. 5.]]


In [24]:
# exercise 1
i_hat = np.array([2, 0])
j_hat = np.array([0, 1.5])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([1, 2])
new_v = basis.dot(v)
print(new_v)

[2. 3.]


In [25]:
# exercise 2
i_hat = np.array([-2, 1])
j_hat = np.array([1, -2])
basis = np.array([i_hat, j_hat]).transpose()
v = np.array([1, 2])
new_v = basis.dot(v)
print(new_v)

[ 0 -3]


In [26]:
# exercise 3
i_hat = np.array([1, 0])
j_hat = np.array([2, 2])
basis = np.array([i_hat, j_hat]).transpose()
determinant = np.linalg.det(basis)
print(determinant)

2.0


In [27]:
# exercise 4

# 2+ linear transformations can be done in a single linear transformation,
# so long as the underlying linear transformations are applied
# in the correct order. For example:
basis1 = np.array([
    [1, 1],
    [0, 1]
])
basis2 = np.array([
    [0, -1],
    [-1, 0]
])
single = basis2 @ basis1
print(single)
v = np.array([2, 1])
new_v = single.dot(v)
print(new_v)

[[ 0 -1]
 [-1 -1]]
[-1 -3]


In [28]:
# exercise 5
A = sympy.Matrix([
    [3, 1, 0],
    [2, 4, 1],
    [3, 1, 8]
])
B = sympy.Matrix([
    54,
    12,
    6
])
X = A.inv() * B
print(X)

Matrix([[99/5], [-27/5], [-6]])


In [29]:
# exercise 6
basis = np.array([
    [2, 1],
    [6, 3]
])
determinant = np.linalg.det(basis)
print(determinant)
print('Linearly independent? -->', determinant != 0.0)

0.0
Linearly independent? --> False


**LINEAR ALGEBRA IS FOUNDATIONAL TO GOOD DATA SCIENCE, LEARN AND MASTER IT**